### ISSUE TITLE
设置开始时间的是有错误出现！

### ISSUE THREAD

**Issue by soho176** [zzh-blog/MovieCut#1]
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    CuttingStart = int(input('设置开始时间：'))
ValueError: invalid literal for int() with base 10: '4.6'

我设置的开始时间是从4.6秒开始截取。出现这个错误，然后就是把参数设置完了之后，如何开始那？找不到开始的地方。

**Comment by Rikka-Sei** [comment]
代码里面int改float即可解决，没有怎么优化，其实精确操作视频还是要掌握ffmpeg的命令含义

**Comment by Rikka-Sei** [comment]
ffmpeg剪切的使用方法可以参考这里 
 http://trac.ffmpeg.org/wiki/Seeking

我的程序把int改float可以执行，但似乎无法做到0.1秒级别的剪切，具体实现就要改进代码了
